# Generated by Django 5.0.8 on 2026-06-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='dedupe_key',
            field=models.CharField(blank=True, db_index=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='duplicate_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='is_qualified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='searchcampaign',
            name='source_counts',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='exportrecord',
            name='export_format',
            field=models.CharField(choices=[('csv', 'CSV'), ('xlsx', 'Excel XLSX'), ('json', 'JSON')], max_length=30),
        ),
    ]
