# Generated by Django 5.0.8 on 2026-06-16 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_lead_dedupe_key_lead_duplicate_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcampaign',
            name='llm_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchcampaign',
            name='search_plan',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
